import { useMemo, useState } from 'react';
import { Box, CardContent, Drawer, Grid, InputAdornment, MenuItem, Select, Stack, Table, TableBody, TableCell, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import { PageHeader } from '../components/common/PageHeader';
import { usePlatformQuery } from '../hooks/usePlatformQuery';
import { incidentService, rootCauseService } from '../services/platformServices';
import type { Incident } from '../types/backend';
import { StatusPill } from '../components/common/StatusPill';
import { GlassCard } from '../components/common/GlassCard';
import { IncidentTimeline } from '../components/visual/IncidentTimeline';

export function IncidentsPage() {
  const { data = [] } = usePlatformQuery(['incidents'], incidentService.list);
  const rca = usePlatformQuery(['rca-recommendations'], rootCauseService.recommendations);
  const [query, setQuery] = useState(''); const [service, setService] = useState('ALL'); const [page, setPage] = useState(0); const [selected, setSelected] = useState<Incident | null>(null);
  const services = ['ALL', ...new Set(data.map((i) => i.serviceName))];
  const filtered = useMemo(() => data.filter((i) => (service === 'ALL' || i.serviceName === service) && JSON.stringify(i).toLowerCase().includes(query.toLowerCase())), [data, query, service]);
  return <><PageHeader eyebrow="Incident Management" title="Enterprise Incident Explorer" description="Search, filter, paginate, and inspect incidents returned by GET /incidents with RCA context from /analysis/recommendations." action={<StatusPill value={`${filtered.length} MATCHES`} />} />
    <GlassCard glow="#38bdf8"><CardContent sx={{ p: 2.5 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ mb: 2.5 }}><TextField fullWidth placeholder="Search incidents, exceptions, endpoints..." value={query} onChange={(e) => setQuery(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><SearchIcon /></InputAdornment> }} /><Select value={service} onChange={(e) => setService(e.target.value)} sx={{ minWidth: 220 }}>{services.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></Stack><Table><TableHead><TableRow><TableCell>Incident ID</TableCell><TableCell>Service</TableCell><TableCell>Severity</TableCell><TableCell>Status</TableCell><TableCell>Timestamp</TableCell><TableCell>Root Cause Status</TableCell></TableRow></TableHead><TableBody>{filtered.slice(page * 8, page * 8 + 8).map((i) => <TableRow key={i.id} hover onClick={() => setSelected(i)} sx={{ cursor: 'pointer', '&:hover': { bgcolor: 'rgba(56,189,248,.06)' } }}><TableCell><Typography fontWeight={900}>#{i.id}</Typography></TableCell><TableCell>{i.serviceName}</TableCell><TableCell><StatusPill value={i.statusCode >= 500 ? 'HIGH' : 'MEDIUM'} /></TableCell><TableCell>{i.statusCode}</TableCell><TableCell>{new Date(i.timestamp).toLocaleString()}</TableCell><TableCell><StatusPill value="AI_ANALYZED" /></TableCell></TableRow>)}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} onPageChange={(_, p) => setPage(p)} rowsPerPage={8} rowsPerPageOptions={[8]} /></CardContent></GlassCard>
    <Drawer anchor="right" open={Boolean(selected)} onClose={() => setSelected(null)} PaperProps={{ sx: { width: { xs: '100%', md: 560 }, bgcolor: 'rgba(5,7,18,.96)', backdropFilter: 'blur(24px)', p: 3 } }}>{selected && <Box><Stack direction="row" justifyContent="space-between" alignItems="flex-start"><Box><Typography variant="h4">Incident #{selected.id}</Typography><Typography color="text.secondary">{selected.serviceName} · {selected.endpoint}</Typography></Box><StatusPill value={selected.statusCode >= 500 ? 'HIGH' : 'MEDIUM'} /></Stack><Grid container spacing={2} sx={{ mt: 2 }}>{[['Status', selected.statusCode], ['Latency', `${selected.latency}ms`], ['Exception', selected.exceptionType], ['Version', selected.version]].map(([k, v]) => <Grid item xs={6} key={k}><GlassCard glow="#8b5cf6"><CardContent><Typography variant="overline" color="text.secondary">{k}</Typography><Typography variant="h6">{v}</Typography></CardContent></GlassCard></Grid>)}</Grid><Typography variant="h6" sx={{ mt: 3 }}>AI Summary</Typography><Typography color="text.secondary">RootPilot detected a probable {selected.exceptionType} fault pattern in {selected.serviceName}. The incident is correlated with dependency pressure and elevated latency.</Typography><Typography variant="h6" sx={{ mt: 3 }}>Root Cause Evidence</Typography>{rca.data?.filter((r) => r.serviceName === selected.serviceName).map((r) => <GlassCard glow="#ef4444" sx={{ mt: 1 }} key={r.recommendation}><CardContent><StatusPill value={r.riskLevel} /><Typography sx={{ mt: 1 }} fontWeight={900}>{r.recommendation}</Typography><Typography color="text.secondary">{r.reason}</Typography></CardContent></GlassCard>)}<Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Modern Incident Timeline</Typography><IncidentTimeline steps={[{ title: 'Detected', description: `${selected.exceptionType} captured on ${selected.endpoint}`, time: selected.timestamp }, { title: 'Correlated', description: 'RootPilot matched service, exception, and latency signals.' }, { title: 'RCA generated', description: `Probable fault pattern assigned to ${selected.serviceName}.` }, { title: 'Recommendation queued', description: 'AI remediation guidance is ready for operator approval.' }]} /></Box>}</Drawer>
  </>;
}
