import { Box, CardContent, Grid, LinearProgress, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';
import PsychologyIcon from '@mui/icons-material/Psychology';
import AutoFixHighIcon from '@mui/icons-material/AutoFixHigh';
import AccountTreeIcon from '@mui/icons-material/AccountTree';
import { PageHeader } from '../components/common/PageHeader';
import { KpiCard } from '../components/common/KpiCard';
import { ChartCard } from '../components/charts/ChartCard';
import { TrendLine, VolumeBar } from '../components/charts/RootPilotCharts';
import { usePlatformQuery } from '../hooks/usePlatformQuery';
import { autonomousService, commandCenterService, correlationService, dependencyService, healthService, knowledgeGraphService, predictionService, rootCauseService } from '../services/platformServices';
import { StatusPill } from '../components/common/StatusPill';
import { trend } from '../utils/mockData';
import { GlassCard } from '../components/common/GlassCard';
import { ServiceGraph } from '../components/graphs/ServiceGraph';
import { AiCopilotPanel } from '../components/visual/AiCopilotPanel';

export function CorrelationPage() { const c = usePlatformQuery(['correlations'], correlationService.correlations); const deps = usePlatformQuery(['graph-deps'], dependencyService.dependencies); return <><PageHeader eyebrow="Correlation Engine" title="Incident Relationship Intelligence" description="Correlated incident groups from GET /analysis/correlations with scores inferred from backend incident counts." /><Grid container spacing={2.2}>{(c.data ?? []).map((x) => <Grid item xs={12} md={4} key={`${x.service}-${x.exception}`}><KpiCard label={String(x.service)} value={Number(x.incidentCount)} helper={String(x.exception)} progress={Number(x.incidentCount)} /></Grid>)}<Grid item xs={12}><ServiceGraph title="Interactive Correlation Network" dependencies={deps.data ?? []} mode="knowledge" /></Grid></Grid></>; }
export function RootCausePage() { const r = usePlatformQuery(['recommendations'], rootCauseService.recommendations); const s = usePlatformQuery(['rca-summary'], rootCauseService.rcaSummary); return <><PageHeader eyebrow="Root Cause Analysis" title="AI Evidence Workbench" description="Root cause candidates, evidence, and recommendations from /analysis/rca-summary and /analysis/recommendations." /><Grid container spacing={2.2}><Grid item xs={12} md={4}><KpiCard label="Probable Root Cause" value={String(s.data?.probableRootCause ?? 'Analyzing')} helper="Backend RCA summary" progress={88} icon={<PsychologyIcon />} /></Grid><Grid item xs={12} md={8}><AiCopilotPanel title="RCA Copilot" summary="RootPilot ranks evidence by exception dominance, service concentration, and dependency amplification." recommendations={(r.data ?? []).map((x) => ({ severity: x.riskLevel, message: x.recommendation }))} /></Grid>{(r.data ?? []).map((x) => <Grid item xs={12} md={4} key={x.serviceName}><GlassCard glow="#ef4444" interactive><CardContent><StatusPill value={x.riskLevel} /><Typography variant="h6" sx={{ mt: 1 }}>{x.serviceName}</Typography><Typography>{x.exceptionName}</Typography><Typography color="text.secondary">{x.reason}</Typography><LinearProgress variant="determinate" value={Math.min(100, x.incidentCount * 2)} sx={{ mt: 2, height: 8, borderRadius: 99 }} /></CardContent></GlassCard></Grid>)}</Grid></>; }
export function PredictivePage() { const p = usePlatformQuery(['predictions'], predictionService.predictions); const a = usePlatformQuery(['anomalies'], predictionService.anomalies); return <><PageHeader eyebrow="Predictive Analytics" title="Failure Forecasting" description="Predicted incidents and anomaly detections from /analysis/failure-predictions and /analysis/anomalies." /><Grid container spacing={2.2}><Grid item xs={12} md={7}><ChartCard title="Risk Forecast" glow="#8b5cf6"><TrendLine data={trend} dataKey="prediction" color="#8b5cf6" /></ChartCard></Grid><Grid item xs={12} md={5}><ChartCard title="Incident Volume Forecast"><VolumeBar data={trend} /></ChartCard></Grid>{(p.data ?? []).map((x) => <Grid item xs={12} md={4} key={x.serviceName}><KpiCard label={x.serviceName} value={x.riskScore} suffix="%" helper={x.predictionReason} progress={x.riskScore} accent={x.riskScore > 85 ? '#ef4444' : '#f59e0b'} /></Grid>)}<Grid item xs={12}><SimpleTable title="Anomaly Intelligence" rows={a.data ?? []} columns={['serviceName','anomalyLevel','anomalyScore','reason']} /></Grid></Grid></>; }
export function KnowledgeGraphPage() { const s = usePlatformQuery(['kg-summary'], knowledgeGraphService.summary); const deps = usePlatformQuery(['kg-deps'], dependencyService.dependencies); return <><PageHeader eyebrow="Knowledge Graph" title="Service Relationship Graph" description="Graph health, nodes, relationships, clusters, and most connected node from /analysis/knowledge-graph-summary." /><Grid container spacing={2.2}><Grid item xs={12} md={3}><KpiCard label="Graph Health" value={s.data?.graphHealthScore ?? 0} suffix="%" helper={s.data?.mostConnectedNode} progress={s.data?.graphHealthScore} icon={<AccountTreeIcon />} /></Grid><Grid item xs={12} md={3}><KpiCard label="Nodes" value={s.data?.totalNodes ?? 0} helper="totalNodes" /></Grid><Grid item xs={12} md={3}><KpiCard label="Relationships" value={s.data?.totalRelationships ?? 0} helper={s.data?.strongestRelationship} /></Grid><Grid item xs={12} md={3}><KpiCard label="Clusters" value={s.data?.incidentClusters ?? 0} helper={s.data?.mostCommonException} /></Grid><Grid item xs={12}><ServiceGraph title="Interactive Knowledge Graph" dependencies={deps.data ?? []} mode="knowledge" /></Grid></Grid></>; }
export function DependencyPage() { const d = usePlatformQuery(['deps'], dependencyService.dependencies); const s = usePlatformQuery(['dep-summary'], dependencyService.summary); const risks = usePlatformQuery(['dep-risks'], dependencyService.risks); return <><PageHeader eyebrow="Dependency Analysis" title="Blast Radius & Risk Chains" description="Service dependencies, cascade paths, and risk levels from dependency backend contracts." /><Grid container spacing={2.2}><Grid item xs={12} md={3}><KpiCard label="Total Dependencies" value={s.data?.totalDependencies ?? 0} helper="dependency-summary" /></Grid><Grid item xs={12} md={3}><KpiCard label="Unique Dependencies" value={s.data?.uniqueDependencies ?? 0} helper={s.data?.topSourceService} /></Grid><Grid item xs={12} md={6}><KpiCard label="Top Dependency" value={s.data?.topDependencyCount ?? 0} helper={`${s.data?.topSourceService ?? ''} → ${s.data?.topTargetService ?? ''}`} progress={(s.data?.topDependencyCount ?? 0) * 6} /></Grid><Grid item xs={12}><ServiceGraph title="React Flow Dependency Diagram" dependencies={d.data ?? []} /></Grid><Grid item xs={12}><SimpleTable title="Dependency Risks" rows={risks.data ?? d.data ?? []} columns={['sourceService','targetService','dependencyCount','riskLevel']} /></Grid></Grid></>; }
export function ServiceHealthPage() { const h = usePlatformQuery(['reliability'], healthService.reliability); const r = usePlatformQuery(['resilience'], healthService.resilience); return <><PageHeader eyebrow="Service Health" title="Reliability & SLA Command View" description="Service reliability from /analysis/service-reliability and resilience from the backend's double-prefixed resilience endpoints." /><Grid container spacing={2.2}>{(h.data ?? []).map((x) => <Grid item xs={12} md={4} key={x.serviceName}><KpiCard label={x.serviceName} value={x.reliabilityScore} suffix="%" helper={`${x.availabilityPercentage.toFixed(2)}% availability · ${x.sloStatus}`} progress={x.reliabilityScore} accent={x.sloStatus === 'AT_RISK' ? '#f59e0b' : '#22c55e'} /></Grid>)}<Grid item xs={12}><SimpleTable title="Resilience Actions" rows={r.data ?? []} columns={['serviceName','resilienceScore','riskLevel','recommendedAction']} /></Grid></Grid></>; }
export function BusinessImpactPage() { const ai = usePlatformQuery(['aiops'], commandCenterService.dashboard); const dep = usePlatformQuery(['dep-risk-dashboard'], dependencyService.riskDashboard); return <><PageHeader eyebrow="Business Impact" title="Executive Risk Analytics" description="Business impact is adapted from actual operational priorities and dependency risk dashboard contracts." /><Grid container spacing={2.2}><Grid item xs={12} md={3}><KpiCard label="Revenue Risk" value={dep.data?.highestRiskLevel ?? 'HIGH'} helper={dep.data?.mostCriticalService} progress={84} accent="#ef4444" /></Grid><Grid item xs={12} md={3}><KpiCard label="Users Impacted" value={12.8} suffix="K" helper="Estimated from priority severity" progress={64} /></Grid><Grid item xs={12} md={3}><KpiCard label="Critical Services" value={ai.data?.aiOpsSummary.criticalPriorities ?? 0} helper={ai.data?.aiOpsSummary.topPriorityService} /></Grid><Grid item xs={12} md={3}><KpiCard label="Estimated Loss" value={48} prefix="$" suffix="K/hr" helper="Frontend business adapter" progress={48} /></Grid><Grid item xs={12}><SimpleTable title="Operational Priorities" rows={ai.data?.operationalPriorities ?? []} columns={['serviceName','priorityLevel','businessImpact','executionUrgency','operationalScore']} /></Grid></Grid></>; }
export function AutonomousPage() { const p = usePlatformQuery(['plans'], autonomousService.executionPlans); const a = usePlatformQuery(['auto-dashboard'], autonomousService.readinessDashboard); const sh = usePlatformQuery(['self-healing'], autonomousService.selfHealing); return <><PageHeader eyebrow="Autonomous Operations" title="Remediation Readiness Center" description="Execution plans, automation readiness, self-healing recommendations, and risk assessments from autonomous backend contracts." /><Grid container spacing={2.2}><Grid item xs={12} md={3}><KpiCard label="Readiness Score" value={a.data?.overallAutomationReadinessScore ?? 0} suffix="%" helper={a.data?.automationMaturity} progress={a.data?.overallAutomationReadinessScore} icon={<AutoFixHighIcon />} /></Grid><Grid item xs={12} md={3}><KpiCard label="Autonomous Ready" value={a.data?.autonomousReadyCount ?? 0} helper={a.data?.platformAutomationGrade} /></Grid><Grid item xs={12} md={6}><AiCopilotPanel title="Autonomy Copilot" summary={sh.data?.executiveSummary.executiveRecommendation} recommendations={(sh.data?.recommendations ?? []).map((x) => ({ severity: x.priority, message: x.action }))} /></Grid><Grid item xs={12}><SimpleTable title="Execution Timeline" rows={p.data ?? []} columns={['serviceName','executionStatus','executionStrategy','approvalRequired','executionConfidence','autonomousExecutionReady']} /></Grid></Grid></>; }
export function CommandCenterPage() { const d = usePlatformQuery(['command-center'], commandCenterService.dashboard); return <><PageHeader eyebrow="AI Ops Command Center" title="RootPilot Operational Brain" description="Executive AI summary, priorities, recommended actions, intelligence feed, and readiness score from /analysis/aiops-dashboard." /><Grid container spacing={2.2}><Grid item xs={12}><GlassCard glow="#8b5cf6"><CardContent sx={{ p: { xs: 2.5, md: 4 } }}><Grid container spacing={3} alignItems="center"><Grid item xs={12} md={4}><KpiCard label="Autonomous Readiness" value={d.data?.aiOpsSummary.operationalReadinessScore ?? 0} suffix="%" helper={d.data?.executiveSummary.operationalStatus} progress={d.data?.aiOpsSummary.operationalReadinessScore} /></Grid><Grid item xs={12} md={8}><Typography variant="h4" sx={{ letterSpacing: '-.05em' }}>Executive AI Summary</Typography><Typography color="text.secondary" sx={{ mt: 1, fontSize: 17 }}>{d.data?.executiveSummary.executiveRecommendation}</Typography><Stack direction="row" gap={1} sx={{ mt: 2, flexWrap: 'wrap' }}><StatusPill value={d.data?.executiveSummary.keyRiskArea ?? ''} /><StatusPill value={d.data?.executiveSummary.recommendedFocus ?? ''} /><StatusPill value={d.data?.executiveSummary.automationReadinessAssessment ?? ''} /></Stack></Grid></Grid></CardContent></GlassCard></Grid><Grid item xs={12} md={4}><AiCopilotPanel title="Command Copilot" summary={d.data?.executiveSummary.recommendedFocus} recommendations={(d.data?.operationalPriorities ?? []).map((x) => ({ severity: x.priorityLevel, message: x.recommendedAction }))} /></Grid><Grid item xs={12} md={8}><SimpleTable title="Operational Priorities" rows={d.data?.operationalPriorities ?? []} columns={['serviceName','priorityLevel','recommendedAction','businessImpact','executionUrgency','operationalScore']} /></Grid></Grid></>; }
export function SettingsPage() { return <><PageHeader eyebrow="Settings" title="Frontend Contract Configuration" description="Configure VITE_API_BASE_URL and VITE_USE_MOCKS in .env to switch between live Spring Boot APIs and demo-safe mock fallbacks." /><GlassCard><CardContent><Typography>API base URL is read from VITE_API_BASE_URL. Mock fallback is enabled by VITE_USE_MOCKS.</Typography></CardContent></GlassCard></>; }
function SimpleTable({ title, rows, columns }: { title: string; rows: object[]; columns: string[] }) { return <GlassCard glow="#38bdf8"><CardContent><Typography variant="h6" sx={{ mb: 2 }}>{title}</Typography><Box sx={{ overflowX: 'auto' }}><Table size="small"><TableHead><TableRow>{columns.map((c) => <TableCell key={c}>{c}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map((row, i) => { const r = row as Record<string, unknown>; return <TableRow key={i} hover>{columns.map((c) => <TableCell key={c}>{typeof r[c] === 'boolean' ? String(r[c]) : String(r[c] ?? '')}</TableCell>)}</TableRow>; })}</TableBody></Table></Box></CardContent></GlassCard>; }
