import type { AIOpsDashboard, Alert, AnomalyDetection, AutomationReadiness, AutomationReadinessDashboard, AutonomousAction, AutonomousExecutionPlan, CascadeFailure, DashboardSnapshot, DashboardSummary, DependencyImpact, DependencyRisk, DependencyRiskDashboard, DependencyRiskScore, DependencySummary, FailurePrediction, Incident, KnowledgeGraphSummary, OperationalPriority, RootCauseRecommendation, SelfHealingDashboard, ServiceDependency, ServiceReliability, ServiceResilience } from '../types/backend';

export const palette = ['#38bdf8', '#8b5cf6', '#22c55e', '#f59e0b', '#ef4444', '#14b8a6'];

export const mockIncidents: Incident[] = [
  { id: 1042, serviceName: 'checkout-service', endpoint: '/api/orders', statusCode: 503, latency: 1820, exceptionType: 'TimeoutException', version: 'v2.7.4', timestamp: '2026-06-04T09:32:00' },
  { id: 1041, serviceName: 'payment-service', endpoint: '/api/payments/authorize', statusCode: 500, latency: 940, exceptionType: 'NullPointerException', version: 'v3.1.0', timestamp: '2026-06-04T09:18:00' },
  { id: 1040, serviceName: 'inventory-service', endpoint: '/api/stock/reserve', statusCode: 429, latency: 720, exceptionType: 'RateLimitException', version: 'v1.9.8', timestamp: '2026-06-04T08:57:00' },
  { id: 1039, serviceName: 'auth-service', endpoint: '/oauth/token', statusCode: 401, latency: 420, exceptionType: 'JwtValidationException', version: 'v4.0.1', timestamp: '2026-06-04T08:40:00' },
];

export const dashboardSummary: DashboardSummary = { totalIncidents: 128, topService: 'checkout-service', topException: 'TimeoutException', severity: 'HIGH', alertsCount: 7, scoredAlertsCount: 4, topCorrelation: 'checkout-service|TimeoutException', topDependency: 'checkout-service->payment-service', highestDependencyRisk: 'CRITICAL', totalDependencies: 18 };
export const dashboardSnapshot: DashboardSnapshot = { dashboard: { ...dashboardSummary, executiveSummary: 'RootPilot AI is tracking elevated checkout latency with payment authorization as the most likely dependency amplifier.', healthScore: 82, systemStatus: 'DEGRADED' }, healthScore: 82, systemStatus: 'DEGRADED', liveSummary: '128 incidents observed. checkout-service is currently the most unstable service.', topDependency: 'checkout-service->payment-service', highestDependencyRisk: 'CRITICAL' };
export const trend = Array.from({ length: 12 }, (_, i) => ({ hour: `${String(i + 8).padStart(2, '0')}:00`, count: [12, 18, 16, 25, 31, 29, 42, 56, 48, 38, 33, 28][i], health: [96, 94, 93, 91, 88, 87, 84, 78, 80, 82, 84, 86][i], prediction: [89, 90, 91, 90, 92, 93, 94, 92, 95, 96, 95, 97][i] }));
export const severityDistribution = [{ name: 'LOW', value: 42 }, { name: 'MEDIUM', value: 51 }, { name: 'HIGH', value: 27 }, { name: 'CRITICAL', value: 8 }];
export const alerts: Alert[] = [{ severity: 'CRITICAL', message: 'Recent checkout failure spike detected' }, { severity: 'HIGH', message: 'TimeoutException is dominant across correlated incidents' }, { severity: 'HIGH', message: 'Strong correlation detected: checkout-service with payment-service' }];
export const serviceDependencies: ServiceDependency[] = [
  { sourceService: 'checkout-service', targetService: 'payment-service', dependencyCount: 14 },
  { sourceService: 'checkout-service', targetService: 'inventory-service', dependencyCount: 9 },
  { sourceService: 'payment-service', targetService: 'bank-gateway', dependencyCount: 7 },
  { sourceService: 'auth-service', targetService: 'user-service', dependencyCount: 5 },
];
export const dependencySummary: DependencySummary = { totalDependencies: 35, uniqueDependencies: 4, topSourceService: 'checkout-service', topTargetService: 'payment-service', topDependencyCount: 14 };
export const dependencyRisks: DependencyRisk[] = serviceDependencies.map((d) => ({ ...d, riskLevel: d.dependencyCount > 10 ? 'CRITICAL' : d.dependencyCount > 6 ? 'HIGH' : 'MEDIUM' }));
export const dependencyImpacts: DependencyImpact[] = serviceDependencies.map((d, i) => ({ sourceService: d.sourceService, impactedService: d.targetService, impactLevel: dependencyRisks[i].riskLevel, impactScore: Math.min(100, d.dependencyCount * 7) }));
export const dependencyRiskScores: DependencyRiskScore[] = dependencyImpacts.map((i) => ({ service: i.impactedService, impactScore: i.impactScore, riskLevel: i.impactLevel }));
export const dependencyRiskDashboard: DependencyRiskDashboard = { totalDependencies: 35, highImpactDependencies: 3, mostCriticalService: 'payment-service', highestRiskLevel: 'CRITICAL', dependencyHealth: 'WATCH', executiveRecommendation: 'Reduce checkout/payment coupling before the next peak window.' };
export const cascades: CascadeFailure[] = [{ sourceService: 'checkout-service', middleService: 'payment-service', targetService: 'bank-gateway' }];
export const predictions: FailurePrediction[] = [
  { serviceName: 'checkout-service', incidentCount: 48, alertCount: 4, dependencyRisk: 14, riskScore: 92, predictedRisk: 'CRITICAL', predictionReason: 'Failure volume and dependency concentration are increasing together.' },
  { serviceName: 'payment-service', incidentCount: 34, alertCount: 3, dependencyRisk: 9, riskScore: 84, predictedRisk: 'HIGH', predictionReason: 'Authorization latency aligns with checkout incident spikes.' },
  { serviceName: 'inventory-service', incidentCount: 21, alertCount: 1, dependencyRisk: 5, riskScore: 63, predictedRisk: 'MEDIUM', predictionReason: 'Rate limits are approaching capacity thresholds.' },
];
export const anomalies: AnomalyDetection[] = predictions.map((p) => ({ serviceName: p.serviceName, incidentCount: p.incidentCount, averageCount: 18, deviation: p.incidentCount - 18, anomalyScore: p.riskScore, anomalyLevel: p.predictedRisk, reason: p.predictionReason }));
export const recommendations: RootCauseRecommendation[] = predictions.map((p) => ({ serviceName: p.serviceName, exceptionName: p.serviceName === 'checkout-service' ? 'TimeoutException' : 'NullPointerException', incidentCount: p.incidentCount, riskLevel: p.predictedRisk, recommendation: `Prioritize ${p.serviceName} remediation workflow`, priority: p.predictedRisk, reason: p.predictionReason }));
export const reliability: ServiceReliability[] = predictions.map((p) => ({ serviceName: p.serviceName, incidentCount: p.incidentCount, reliabilityScore: 100 - Math.round(p.riskScore / 2), availabilityPercentage: 99.95 - p.riskScore / 100, sloTarget: 99.9, sloStatus: p.riskScore > 80 ? 'AT_RISK' : 'HEALTHY', riskLevel: p.predictedRisk }));
export const resilience: ServiceResilience[] = reliability.map((r) => ({ serviceName: r.serviceName, resilienceScore: r.reliabilityScore, riskLevel: r.riskLevel, recommendedAction: r.sloStatus === 'AT_RISK' ? 'Enable safe rollback and horizontal scaling' : 'Continue monitoring' }));
export const autonomousActions: AutonomousAction[] = recommendations.map((r) => ({ actionType: 'REMEDIATE', serviceName: r.serviceName, triggerSource: 'RootPilot AI', severity: r.riskLevel, recommendedAction: r.recommendation, status: 'PENDING_APPROVAL', reason: r.reason }));
export const executionPlans: AutonomousExecutionPlan[] = autonomousActions.map((a) => ({ serviceName: a.serviceName, recommendedAction: a.recommendedAction, executionStatus: 'SIMULATED', executionStrategy: 'Canary remediation with automatic rollback', approvalRequired: a.severity !== 'LOW', executionConfidence: a.severity === 'CRITICAL' ? 86 : 78, autonomousExecutionReady: a.severity !== 'CRITICAL' }));
export const automationReadiness: AutomationReadiness[] = executionPlans.map((p) => ({ serviceName: p.serviceName, recommendedAction: p.recommendedAction, automationRisk: p.approvalRequired ? 'HIGH' : 'LOW', executionConfidence: p.executionConfidence, rollbackReady: true, approvalRequired: p.approvalRequired, autonomousExecutionReady: p.autonomousExecutionReady }));
export const automationDashboard: AutomationReadinessDashboard = { totalRecommendations: 3, autonomousReadyCount: 2, approvalRequiredCount: 1, averageExecutionConfidence: 83, overallAutomationReadinessScore: 78, automationMaturity: 'ASSISTED_AUTONOMY', platformAutomationGrade: 'B+', topAutomationRisk: 'checkout-service' };
export const selfHealingDashboard: SelfHealingDashboard = { recommendations: automationReadiness.map((a) => ({ serviceName: a.serviceName, action: a.recommendedAction, priority: a.automationRisk, triggerReason: 'Backend self-healing contract', automationEligible: a.autonomousExecutionReady })), summary: { totalRecommendations: 3, automationEligibleCount: 2, criticalActions: 1, topRecommendedAction: 'Canary remediation', averageAutomationReadiness: 81 }, executiveSummary: { overallAutomationReadiness: 78, selfHealingMaturity: 'ASSISTED_AUTONOMY', highestPriorityAction: 'checkout-service remediation', automationCoverage: 66, executiveRecommendation: 'Approve high-confidence remediations for non-critical paths.' } };
export const priorities: OperationalPriority[] = predictions.map((p) => ({ serviceName: p.serviceName, priorityLevel: p.predictedRisk, recommendedAction: `Stabilize ${p.serviceName}`, businessImpact: p.riskScore > 85 ? 'Revenue checkout path' : 'Customer experience', executionUrgency: p.predictedRisk, operationalScore: 100 - p.riskScore / 2 }));
export const aiopsDashboard: AIOpsDashboard = { operationalPriorities: priorities, aiOpsSummary: { totalPriorities: 3, criticalPriorities: 1, highPriorities: 1, servicesRequiringAction: 3, averageOperationalScore: 61, operationalReadinessScore: 78, topPriorityService: 'checkout-service' }, executiveSummary: { operationalStatus: 'DEGRADED', keyRiskArea: 'Checkout conversion path', recommendedFocus: 'Payment dependency isolation', automationReadinessAssessment: 'Assisted autonomy ready', executiveRecommendation: 'Approve remediation simulation and scale checkout workers.' } };
export const knowledgeSummary: KnowledgeGraphSummary = { totalNodes: 8, totalRelationships: 10, mostConnectedNode: 'checkout-service', strongestRelationship: 'checkout-service->payment-service', strongestRelationshipStrength: 94, graphDensity: 0.42, incidentClusters: 2, mostCommonException: 'TimeoutException', graphMaturityScore: 84, relationshipDiversityScore: 71, graphHealthScore: 82 };
